config/routes.rb
Rails.application.routes.draw do
  root 'pod_libraries#index'

  resources :pods, controller: :pod_libraries, only: [:index, :show]
  resources :authors, only: [:show]
end

app/models/author.rb
# == Schema Information
#
# Table name: authors
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Author < ActiveRecord::Base
  has_many :authorings
  has_many :pods, through: :authorings, source: :pod
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    @page_title = "Pods by #{@author.name}"

    pods_scope = @author.pods
    @order_type = params[:o] || 'popularity'
    pods_scope = pods_scope.sort(@order_type)
    @pods = pods_scope.page(params[:page]).per(10)

    respond_to do |format|
      format.html
      format.js
      format.json
    end
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render action: 'show', status: :created, location: @author }
      else
        format.html { render action: 'new' }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.where(id: params[:id]).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params[:author]
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.haml
= form_for @author do |f|
  - if @author.errors.any?
    #error_explanation
      %h2= "#{pluralize(@author.errors.count, "error")} prohibited this author from being saved:"
      %ul
        - @author.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/authors/edit.html.haml
%h1 Editing author

= render 'form'

= link_to 'Show', @author
\|
= link_to 'Back', authors_path

app/views/authors/new.html.haml
%h1 New author

= render 'form'

= link_to 'Back', authors_path

app/views/authors/show.html.haml
.search-container
  .row.collapse
    .small-12.columns
      %h1.author-header
        = title
.results-container
  = render 'results', pods: @pods, order_type: @order_type