config/routes.rb
Rails.application.routes.draw do
  root 'pod_libraries#index'

  resources :pods, controller: :pod_libraries, only: [:index, :show]
  resources :authors, only: [:show]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
  def time_ago(datetime)
    datetime ? time_ago_in_words(datetime) + ' ago' : '-'
  end
end

app/views/application/_footer.html.haml
.footer
  .row.collapse
    .medium-4.columns.contributors
      = link_to 'Built by @luvtechno', 'https://github.com/luvtechno'
      %br
      and
      %br
      = link_to 'contributors', 'https://github.com/luvtechno/cocoapods_search/graphs/contributors'
    .medium-4.columns.sponsor
      = link_to 'https://www.wantedly.com/' do
        Sponsored
        by
        Wantedly, Inc.
        .logo
          = image_tag 'wantedly.png'
    .medium-4.columns
      .github-buttons
        %iframe{ src: "http://ghbtns.com/github-btn.html?user=luvtechno&type=follow&count=true",
    allowtransparency: "true", frameborder: "0", scrolling: "0", width: "165", height: "20" }
        %br
        %iframe{ src: "http://ghbtns.com/github-btn.html?user=luvtechno&repo=cocoapods_search&type=watch&count=true",
    allowtransparency: "true", frameborder: "0", scrolling: "0", width: "115", height: "20" }

app/views/application/_ga.html.erb
<script>
<% if Rails.env.production? %>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-12847756-33', 'wantedly.com');
  ga('send', 'pageview');
<% end %>
</script>

app/views/application/_pod.html.haml
- rank ||= pod.rank
- show_detail ||= false
.row.collapse.result
  .medium-1.column.rank
    = link_to pod_path(pod) do
      .rank-number
        = rank
  .medium-8.columns
    .row.collapse
      .small-12.columns.title
        %h3
          = link_to pod.name, pod.homepage
          %span.version
            = pod.current_version
          %span.date
            released:
            = time_ago pod.current_version_released_at
    .row.collapse.summary
      .small-12.columns
        = pod.summary
    - if show_detail && pod.description
      .row.collapse.description
        .small-12.columns
          = pod.description
    .row.collapse.stats.hide-for-small-only
      .small-3.medium-2.columns
        .key
          %i.fi-heart
          Popularity
        .value
          = pod.popularity
      .small-3.medium-2.columns
        .key
          %i.fi-social-github
          Contoributors
        .value
          = pod.github_contributor_count || '-'
      .small-3.medium-2.columns
        .key
          %i.fi-star
          Stars
        .value
          = pod.github_stargazer_count || '-'
      .small-3.medium-6.columns
        .key
          %i.fi-clock
          Last Commit
        .value
          = time_ago pod.last_committed_at
    .row.collapse.stats.show-for-small-only
      .small-6.columns.key
        %i.fi-heart
        Popularity
      .small-6.columns.value
        = pod.popularity
    .row.collapse.stats.show-for-small-only
      .small-6.columns.key
        %i.fi-social-github
        Contoributors
      .small-6.columns.value
        = pod.github_contributor_count || '-'
    .row.collapse.stats.show-for-small-only
      .small-6.columns.key
        %i.fi-star
        Stargazers
      .small-6.columns.value
        = pod.github_stargazer_count || '-'
    .row.collapse.stats.show-for-small-only
      .small-6.columns.key
        %i.fi-clock
        Last Commit
      .small-6.columns.value
        = time_ago pod.last_committed_at
  .medium-3.columns.text-center
    .row.collapse.links
      .small-12.columns
        = link_to pod.documentation_url, class: 'button tiny' do
          %i.fi-page
          Docs
        = link_to pod.spec_url, class: 'button tiny' do
          %i.fi-widget
          Spec
        = link_to pod.github_url, class: 'button tiny' do
          %i.fi-social-github
          GitHub
        = link_to "https://github.com/search?l=&q=#{pod.name}+path%3APodfile&type=Code", class: 'button tiny' do
          %i.fi-magnifying-glass
          Samples
    .row.collapse.authors
      .small-12.columns
        Author(s)
        %ul
          - pod.authors.each_with_index do |author, i|
            %li
              = link_to author.name, author_path(author)

app/views/application/_results.html.haml
.row.collapse.sort-control
  .small-12.columns
    %dl.sub-nav
      %dt ORDER BY:
      - PodLibrary::ORDER_TYPES.each do |type|
        - if type == order_type
          %dd.active
            %a
              %i{ class: icon_class(type) }
              = type.titlecase
        - else
          %dd
            = link_to url_for(o: type, q: params[:q]) do
              %i{ class: icon_class(type) }
              = type.titlecase

#loading.row.collapse
  = image_tag 'loading.gif'
#results
  - pods.each.with_index(1 + pods.offset_value) do |pod, rank|
    = render 'pod', pod: pod, rank: rank
  .row.collapse
    .small-12.columns.text-center
      = paginate pods